### ISSUE TITLE
Chart not working

### ISSUE THREAD

**Issue by pawerak** [roest01/docker-speedtest-analyser#41]
I use docker-compose:
```
version: "3.2"
services:
  speedtest:
    container_name: speedtest
    image: roest/docker-speedtest-analyser
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./speedtest/data:/var/www/html/data
    ports:
      - 8090:80
      - 4343:443
    environment:
      - CRONJOB_ITERATION=30
```
Script is working properly. File result.csv is updating every 30 min, but the webpage is not updating.
![Przechwytywanie](https://user-images.githubusercontent.com/60275240/76170628-1ab70200-6184-11ea-8acd-7da2e0e4ae75.PNG)

Logs:
```
Starting run.sh
Starting Cronjob
Starting nginx
--- running speedtest ---
running with default server
ran
Ping: 26.528 ms
Download: 174.51 Mbit/s
Upload: 16.86 Mbit/s

08.03.2020 20:00:29
('08.03.2020 20:00:29', '26.52', '174.', '16.8')
speedtest complete
--- running speedtest ---
running with default server
ran
Ping: 19.655 ms
Download: 171.36 Mbit/s
Upload: 17.73 Mbit/s

08.03.2020 20:30:30
('08.03.2020 20:30:30', '19.65', '171.', '17.7')
speedtest complete
```
