### ISSUE TITLE
No WebUI behind traefik

### ISSUE THREAD

**Issue by Wyrrrd** [roest01/docker-speedtest-analyser#76]
Hello,

I am serving my microservices behind traefik as a reverse proxy, so each service has its own subdomain. Sadly, speedtest doesn't work that way: traefik registers the service and router rule, detects the service resides on port 80, but when I try to access it, it throws a 404 error.

<details>
<summary><b>docker-compose</b></summary>

```
version: "3"

volumes:
  data:
  
services:

### Speedtest ###
  spd:
    container_name: spd
    image: roest/docker-speedtest-analyser
    restart: unless-stopped
    volumes:
      - data:/var/www/html/data
    environment:
      - CRONJOB_ITERATION=15
    labels:
      - traefik.enable=true
      - traefik.http.routers.spd.rule=Host(`speedtest.example.com`)
      - traefik.http.routers.spd.entrypoints=http
```

</details>

I tried the same config plus mapping a port, then accessing via server domain and port, that worked.
